Print git diff on pre-commit failure

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -69,8 +69,11 @@ jobs:
         env:
           SKIP: nixfmt
         run: |
-          nix develop -c pre-commit run -a
-          git diff --exit-code
+          nix develop -c pre-commit run -a || (
+            echo "pre-commit failed" ;
+            git diff --exit-code ;
+            false
+          )
 
       - name: Run sccache-cache
         uses: mozilla-actions/sccache-action@v0.0.9
